name: Publish NuGet Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore

      - name: Pack
        working-directory: ./src
        run: dotnet pack --no-build -c Release -o out

      - name: Publish
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: VGManager.Adapter.Models/VGManager.Adapter.Models.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
